version: '3.8'

services:
  redis:
    image: redis:alpine
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    volumes:
      - redis_data:/data
    networks:
      - terramino_net

  backend:
    image: terramino-go-backend:latest
    deploy:
      replicas: 2
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TERRAMINO_PORT=8080
    networks:
      - terramino_net
    depends_on:
      - redis

  frontend:
    image: terramino-go-frontend:latest
    deploy:
      replicas: 5
    ports:
      - "8081:8081"
    networks:
      - terramino_net

volumes:
  redis_data:

networks:
  terramino_net:
    driver: overlay
