FROM golang:1.22 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o terramino
RUN go build -o terramino-cli cmd/cli/main.go

FROM ubuntu:latest AS runner

WORKDIR /app

COPY --from=builder /app/terramino .
COPY --from=builder /app/terramino-cli .

EXPOSE 8080

ENV RUN_MODE=server
CMD if [ "$RUN_MODE" = "cli" ]; then ./terramino-cli; else ./terramino; fi
